# apiVersion: v1
# kind: ConfigMap
# metadata: 
#   name: frontend
#   namespace: roboshop
# data:
#   CART_HOST: "cart"
#   CART_PORT: "8080"
#   USER_HOST: "user"
#   USER_PORT: "8080"
#   AMQP_HOST: "rabbitmq"
#   AMQP_USER: "roboshop"
#   AMQP_PASS: "roboshop123"

---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: frontend
#   namespace: roboshop


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: frontend
      tier: frontend
  template:
    metadata:
      labels:
        project: roboshop
        component: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: basha831750/frontend:v1
        imagePullPolicy: Always
        # envFrom:
        # - configMapRef:
        #     name: frontend
        ports:
        - name: liveness-port
          containerPort: 8080
        - name: readiness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
          initialDelaySeconds: 10

        livenessProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 20
          periodSeconds: 15

---




apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 8080 # container port
