apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-conf
  namespace: roboshop
data: 
  # my.cnf:
  #   [mysqlid]
  #   innodb_redo_log_capacity = 2G

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: redis
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: database
  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: database
    spec:
      containers:
      - name: mysql
        image: basha831750/mysql:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 25
      #   volumeMount:
      #     name: mysql-config
      #     mountPath: /etc/mysql/conf.d/my.cnf     # will discuss later 
      #     subPath: my.conf
      # volume:
      #   name: mysql-config
      #   configMap:
      #     name: mysql-conf

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
 selector:
    project: roboshop
    component: mysql
    tier: database
 ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # container port

  